add notebook required for terra workspace
ga4gh/vrs-python pull request #108
Opened 2022-09-09 15:27 UTC by korikuzma

closes #107 

We would like to have the notebooks in Terra by plenary

2022-09-09 15:50 UTC, korikuzma commented
@ahwagner @andreasprlic @larrybabb For some reason the pylint static analysis was failing (even though I didn't touch any files in `src/`), so I just changed single to double quotes in the normalize module

2022-09-13 02:51 UTC, ahwagner requested changes
This all looks well and good, but I think this notebook should come with some built-in directions for creating the Terra workspace that uses this notebook. Without that I cannot test that this performs as expected.

Perhaps @vdauwera can assist with this?

2022-09-16 03:06 UTC, vdauwera commented
> This all looks well and good, but I think this notebook should come with some built-in directions for creating the Terra workspace that uses this notebook. Without that I cannot test that this performs as expected.
> 
> Perhaps @vdauwera can assist with this?

I opened PR https://github.com/ga4gh/vrs-python/pull/110 to address this, lmkwyt

2022-10-04 18:18 UTC, ahwagner approved these changes

2022-10-04 18:24 UTC, merged