Update README for running notebooks
ga4gh/vrs-python pull request #286
Opened 2023-11-18 07:02 UTC by manish0kuniyal

Updated the python version from 3.7 to 3.10.
Provided description about running the notebook on VS Code.

2023-11-20 13:13 UTC, korikuzma requested changes

2023-11-20 13:13 UTC, korikuzma commented on README.md
> +**2.Install Jupyter Extension**: Use Extensions view (Ctrl+Shift+X) to install the Jupyter extension.
```suggestion
**2.Install Jupyter Extension**: Use Extensions view (Ctrl+Shift+X or ⌘+Shift+X) to install the [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter).
```

2023-11-20 13:13 UTC, korikuzma commented on README.md
> +**4.Select Python Interpreter**: In a notebook, click "Select Python Interpreter" and choose your Python 3.10 virtual environment.
```suggestion
**4. Select Jupyter Kernel**: In a notebook, click `Select Kernel` at the top right.  Select the option where the path is `venv/3.10/bin/python3`. See [here](https://code.visualstudio.com/docs/datascience/jupyter-kernel-management) for more information on managing Jupyter Kernels in VS Code.
```

2023-11-20 13:13 UTC, korikuzma commented on README.md
> +**1.Open VS Code**: Launch Visual Studio Code.
```suggestion
**1. Open VS Code**: Launch Visual Studio Code.   
```

2023-11-20 13:13 UTC, korikuzma commented on README.md
> +**2.Install Jupyter Extension**: Use Extensions view (Ctrl+Shift+X) to install the Jupyter extension.
```suggestion
**2. Install Jupyter Extension**: Use Extensions view (Ctrl+Shift+X) to install the Jupyter extension.
```

2023-11-20 13:13 UTC, korikuzma commented on README.md
> +**3.Open Project in VS Code**: Navigate to your project folder and open it in VS Code.
```suggestion
**3. Open Project in VS Code**: Navigate to your project folder and open it in VS Code.   
```

2023-11-20 13:13 UTC, korikuzma commented on README.md
> +
```suggestion
**5. Run Notebook**: After selecting the kernel you can now run the notebook.
```

2023-11-20 15:30 UTC, manish0kuniyal commented
The required changes have been made.

2023-11-20 22:56 UTC, korikuzma approved these changes

2023-11-20 22:58 UTC, korikuzma requested changes

2023-11-20 22:58 UTC, korikuzma commented on README.md
> +[VS Code](https://code.visualstudio.com/) is a code editor developed by Microsoft. It is lightweight, highly customizable, and supports a wide range of programming languages, with a robust extension
```suggestion
[VS Code](https://code.visualstudio.com/) is a code editor developed by Microsoft. It is lightweight, highly customizable, and supports a wide range of programming languages, with a robust extension system. You can download VS Code [here](https://code.visualstudio.com/Download).
```

2023-11-20 22:58 UTC, korikuzma commented on README.md
> +**4. Select Jupyter Kernel**: In a notebook, click `Select Kernel` at the top right.  Select the option where the path is `venv/3.10/bin/python3`. See [here](https://code.visualstudio.com/docs/datasc
```suggestion
**4. Select Jupyter Kernel**: In a notebook, click `Select Kernel` at the top right. Select the option where the path is `venv/3.10/bin/python3`. See [here](https://code.visualstudio.com/docs/datascience/jupyter-kernel-management) for more information on managing Jupyter Kernels in VS Code. 
```

2023-11-20 23:02 UTC, korikuzma requested changes

2023-11-20 23:02 UTC, korikuzma commented on README.md
> +
Remove spaces between number bullets

2023-11-21 04:16 UTC, manish0kuniyal commented on README.md
> +
Done

2023-11-21 13:31 UTC, manish0kuniyal commented on README.md
> +**5.Run Notebook**: After selecting the kernel you can now run the notebook.
Hello again,

I noticed the documentation mentions feedback in pull requests, but is it necessary in this particular case? If so, how should I proceed with providing feedback on this specific pull request? 
Additionally, the necessary modifications in the README have been updated .

2023-11-21 13:33 UTC, korikuzma commented on README.md
> +**5.Run Notebook**: After selecting the kernel you can now run the notebook.
@manish0kuniyal feedback isn't necessary. Please accept the suggested changes to remove the new lines between the number bullets.

2023-11-21 15:35 UTC, manish0kuniyal reviewed
updated

2023-11-21 15:40 UTC, korikuzma requested changes
@manish0kuniyal missed these ones

2023-11-21 15:40 UTC, korikuzma commented on README.md
> +
```suggestion
```

2023-11-21 15:40 UTC, korikuzma commented on README.md
> +
```suggestion
```

2023-11-21 15:40 UTC, korikuzma commented on README.md
> +
```suggestion
```

2023-11-21 15:47 UTC, korikuzma approved these changes

2023-11-21 15:47 UTC, korikuzma commented
@manish0kuniyal thanks for contributing!

2023-11-21 15:47 UTC, merged

2023-11-21 15:51 UTC, manish0kuniyal commented
Thank you, ma'am, for being patient with me and explaining all the things step by step. I hope to contribute more to the Global Alliance for Genomics and Health.