docs: change order in readme
ga4gh/vrs-python pull request #294
Opened 2023-12-11 07:25 UTC by sivangbagri

Solving issue #291

2023-12-12 12:24 UTC, korikuzma requested changes

2023-12-12 12:24 UTC, korikuzma commented on README.md
> +    source venv/3.10/bin/activate
We'd probably want to move the installing for development section here.

2023-12-15 15:39 UTC, larrybabb commented
@korikuzma can you verify this is what you expected. I'll do the merge if you approve it.

2023-12-15 15:49 UTC, korikuzma commented
@sivangbagri Can you pull in the latest changes from main and update your branch?

2023-12-18 12:28 UTC, korikuzma requested changes

2023-12-18 12:28 UTC, korikuzma commented on README.md
> +[Python](https://www.python.org/) | [3.10](https://www.python.org/downloads/release/python-3100/)
```suggestion
[Python 3.10](https://www.python.org/downloads/release/python-3100/)
```

2023-12-18 12:28 UTC, korikuzma commented on README.md
> -    $ source venv/3.10/bin/activate
You can add this back and just make a comment to activate the venv if it's not already

2023-12-19 12:45 UTC, korikuzma requested changes

2023-12-19 12:45 UTC, korikuzma commented on README.md
> +
Move this after lines 60-64

```markdown

Fork the repo at https://github.com/ga4gh/vrs-python/ .

    $ git clone --recurse-submodules git@github.com:YOUR_GITHUB_ID/vrs-python.git
    $ cd vrs-python
    $ make devready

Activate the virtual environment:

    $ source venv/3.10/bin/activate
```

2023-12-19 12:45 UTC, korikuzma commented on README.md
> +
Remove new lines

2023-12-20 16:02 UTC, larrybabb approved these changes
+1

2023-12-20 16:06 UTC, merged