updates to vcf_annotator.md
ga4gh/vrs-python pull request #385
Opened 2024-04-05 17:21 UTC by wesleygoar

Addresses issue-325. Added new options for the vcf_annotator to the vcf_annotator readme.

2024-04-05 17:32 UTC, jsstevenson requested changes

2024-04-05 17:32 UTC, jsstevenson commented on docs/extras/vcf_annotator.md
> +>Show the options available
I would surround the individual options in backticks, eg `--vrs_attribute`.

2024-04-05 17:41 UTC, korikuzma reviewed
I would also reference these docs in the main readme. Possibly where `Annotate VCFs with VRS` is?

2024-04-05 18:24 UTC, wesleygoar commented
> I would also reference these docs in the main readme. Possibly where `Annotate VCFs with VRS` is?

@korikuzma K.

2024-04-05 20:24 UTC, jsstevenson approved these changes

2024-04-10 12:27 UTC, korikuzma requested changes

2024-04-10 13:12 UTC, korikuzma approved these changes

2024-04-10 18:07 UTC, merged