cicd: include precommit
ga4gh/vrs-python pull request #454
Opened 2024-10-29 13:36 UTC by jsstevenson

* Add precommit + some minimally controversial hooks
* Run hooks over existing codebase. There's a few instances of trailing whitespace and incorrect line endings.

TODO
 * put it in github actions

2024-10-29 19:05 UTC, jsstevenson commented on Makefile
> +	pre-commit install
this seems to work for (and make sense to) me but I'm always wary of makefile environment construction soooo

2024-10-30 11:02 UTC, korikuzma commented on submodules/README.md
We shouldn't run checks in submodules dir

2024-10-30 11:10 UTC, korikuzma requested changes
> Not sure if this should be mentioned explicitly in the readme?

This would be nice

2024-10-30 11:40 UTC, jsstevenson commented on .github/workflows/python-cqa.yml
Yes -- was originally using it but it a) doesn't seem particularly necessary, this is like a 4 line action, b) it's maintenance-only, I'm not sure how quick they would be to upgrade dependencies. They suggest `pre-commit.ci lite` but I think this is also some extra heft that we don't necessarily need, I think workflows can be abstracted enough as it is.

2024-10-30 11:46 UTC, jsstevenson commented on submodules/README.md
pre-commit doesn't run on anything in a submodule, unless I'm mistaken. The only affected file in that directory is `submodules/README.md`.

2024-10-30 11:56 UTC, korikuzma commented on submodules/README.md
Ope, my bad. Only saw submodules dir when I was reviewing quickly

2024-10-30 12:02 UTC, korikuzma approved these changes

2024-10-30 12:03 UTC, merged